### ISSUE TITLE
Cadet databases in the source folder are not created

### ISSUE THREAD

**Issue by murdo-moj** [ministryofjustice/data-catalogue#325]
We now ingest some tables from the [sources directory of CaDeT](https://github.com/moj-analytical-services/create-a-derived-table/pull/2312)

However this case is not accounted for in our custom ingestion so the tables [come through to find moj data with incomplete metadata](https://find-moj-data.service.justice.gov.uk/details/table/urn:li:dataset:(urn:li:dataPlatform:dbt,cadet.awsdatacatalog.familyman_live_v4.addresses,PROD)).

### Problems to fix
* Databases are not created for these tables.
* Domains are not assigned to these tables.

### Potential solutions
* Reorder the files in CaDeT so that they are included in domain folders (investigate potential knock-on effects on CaDeT pipelines)
* Adjust the custom ingestion pipelines we have to add databases and domains

**Comment by LavMatt** [comment]
There are some difficulties present in ingesting dbt sources how we want and with the metadata we require and i would now suggest ingesting these sources direct from glue rather than via dbt and create-a-derived-table

The reasons for this are:
1. Source dbt yaml config files are generated in an automated way, scraped from the glue catalog and written to the cadet repo on an automated schedule. This has resulted in our previous alterations to these files being overwritten excluding content we've added.
2. Sources do not follow the cadet convention where models are saved in a folder representative of their domain. They are saved in a `sources` folder and so our ingestion process as is would infer the domain to be Sources.

Workarounds for the issues raised above would require us to make further changes to the cadet codebase and would add further complication to the process which is not overly desired by data engineering (cadet is complex enough already).

There are only a handful of source systems we want to ingest this way and now we have a process setup for ingesting from glue it seems a better way forward to ingest these databases direct from glue, adding in the metadata we need to their individual ingestion recipes.

I will add the `dc_cadet` tags to  sources though as this will ensure anything we have adding to these (eg. tags) will match the state of the cadet repo, which is not currently the case
